# ==============================================================
# = Data Source-1
# ==============================================================
#for IP 10.0.0.8
#spring.housing-datasource.jdbcUrl = jdbc:mysql://10.0.0.8:3306/housing?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
#spring.housing-datasource.username = eisystems
#spring.housing-datasource.password = dpgHajAbMMr3Ypi
#for IP 5.181.255.180
spring.housing-datasource.jdbcUrl = jdbc:mysql://5.181.255.180:3306/housing?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
spring.housing-datasource.username = eisystems
spring.housing-datasource.password = oqo_4lH_tASIrXMst3
#spring.housing-datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ==============================================================
#===============================================================
# Data Source-2
# ==============================================================
#for IP 10.0.0.8
#spring.eisystems-datasource.jdbcUrl = jdbc:mysql://10.0.0.8:3306/eisystems?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
#spring.eisystems-datasource.username = eisystems
#spring.eisystems-datasource.password = dpgHajAbMMr3Ypi
#for IP 5.181.255.180
spring.eisystems-datasource.jdbcUrl = jdbc:mysql://5.181.255.180:3306/eisystems?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
spring.eisystems-datasource.username = eisystems
spring.eisystems-datasource.password = oqo_4lH_tASIrXMst3
#spring.eisystems-datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ==============================================================
# ==============================================================
server.port=8088
#server.port=7776 
#==============================================================
#==============================================================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
# = Keep the connection alive if idle for a long time (needed in production)
# ==============================================================
#spring.datasource.testWhileIdle = true
#spring.datasource.validationQuery = SELECT 1
# ==============================================================
# = Show or not log for each sql query
# ==============================================================
#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.format_sql=true
#hibernate.format_sql=true
#spring.jpa.properties.hibernate.show_sql=true
#hibernate.show_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.type=TRACE
# ==============================================================
# = Hibernate ddl auto (create, create-drop, update)
# ==============================================================
hibernate.ddl-auto = update
# ==============================================================
# = The SQL dialect makes Hibernate generate better SQL for the chosen database
# ==============================================================
hibernate.dialect = org.hibernate.dialect.MySQL55Dialect
# ==============================================================
# = Initialize the database using data.sql script
# ==============================================================
spring.housing-datasource.initialization-mode=always
spring.eisystems-datasource.initialization-mode=always
#===============================================================
#= log info
#===============================================================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.net.guides=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.web=DEBUG
server.error.whitelabel.enabled=false

# ====================LocalData===LocalDateTime=================!
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.mvc.format.time=HH:mm:ss
#===============================================================!
#===============================================================
#spring.devtools.add-properties=false

